### ISSUE TITLE
Error when following Dive Into Hydra instructions

### ISSUE THREAD

**Issue by taliamath** [projecthydra/hydra#102]
In a test Windows environment, I followed the Dive into Hydra instructions. Solr and Fedora started fine, but when I attempt to go to the Blacklight page at localhost:3000 I see the following error:
![capture](https://cloud.githubusercontent.com/assets/13243770/14438214/c134c146-ffd9-11e5-9a0e-78e5e1531c77.PNG)
Any advice would be greatly appreciated.

**Comment by bertrama** [comment]
I don't know that I have great advice for fixing it, but is this still a problem?

**Comment by ericgriffis** [comment]
@taliamath it looks like the Solr server isn't running... did you [start Solr with `solr_wrapper`](https://github.com/projecthydra/hydra/wiki/Lesson---Start-FCRepo-and-Solr#step-1-start-solr) and can you navigate to http://localhost:8983?

**Comment by bess** [comment]
Closing this ticket due to age. @taliamath, would you please give the latest version a try and if you're still having trouble open a new ticket?
