### ISSUE TITLE
Request: Distributing a Gemfile.lock with Dive into Hydra

### ISSUE THREAD

**Issue by bertrama** [projecthydra/hydra#105]
I'd like to request that at least one known working Gemfile.lock be distributed with the Dive into Hydra instructions.  I don't think it should be part of the instructions, but it would be helpful when  [troubleshooting when things break due to dependency changes](https://github.com/projecthydra/hydra/issues/102).

**Comment by jcoyne** [comment]
I'm not sure the solution you propose would fix the problem you've encountered. It looks like you haven't got solr running or you haven't configured Hydra to look in the right place for it. Solr is non-Ruby dependency so we couldn't pin it in the Gemfile. I'd like to hear more about how you think it might help though.

**Comment by bertrama** [comment]
I actually didn't have that problem, but one of my colleagues did.  As did that user.  The command for starting solr  `solr_wrapper -d solr/config/ --collection_name hydra-development` had been failing or had been failing to create the collection.  He had fixed the problem by running `bundle update solr_wrapper`.

**Comment by jcoyne** [comment]
The only thing I can think of that has changed  since hydra was last published was that Solr 6 was released. So if we had a lock file they would have been stuck with a version of the solr config that only worked on Solr 5

**Comment by bertrama** [comment]
I definitely don't want anyone to do extra work to generate a new lock file.  I was just thinking it'd help new people like me know where they went wrong if the lock files that get generated while testing the directions get shared. I'd offer to do this myself, but GitHub doesn't do pull requests for wiki pages.

Like you said, the value sounds to be dubious, and it sounds like it'll be extra work.  Thanks for considering.  I'll go ahead and close this.
