### ISSUE TITLE
Release plan for Hydra 11

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/hydra#117]
- [x] Nokogiri to 1.7
- [x] ActiveFedora to 11.1
- [x] Remove nom-xml
- [x] Remove OM
- [x] Rails to 5.0
- [x] Blacklight to 6.7
- [x] LDP to 0.6
- [x] Hydra-head to 10.3
- [x] Solr_wrapper to latest #116 
- [x] Fcrepo_wrapper to latest
- [x] ActiveTriples to 0.11

**Comment by bess** [comment]
@jcoyne Is that your suggested list of versions that work together? I'd be very happy to give those a try and do a gem release / tutorial update accordingly.

**Comment by jcoyne** [comment]
@bess yes, that's mostly what we're doing in CurationConcerns/Sufia/Hyku development.  Those are the versions I'd expect to work.

**Comment by bess** [comment]
Just submitted pull request for this.

**Comment by bess** [comment]
Fixed in 11.0.0.rc1
