### ISSUE TITLE
Problem in telling blacklight which fields to use in queries and hence search results are not rendered

### ISSUE THREAD

**Issue by shubhanshu-gupta** [projecthydra/hydra#62]
[In the lesson: make blacklight return search results](https://github.com/projecthydra/hydra/wiki/Lesson%3A-make-blacklight-return-search-results)   everything works well till step 2 (I mean, the blacklight search interface shows up well and as expected - the search keyword 'Anna' doesn't return any results because till step 2 we didn't tell Blacklight which fields to search in). 

But as soon as I re-run the rails server after amending:
``` 
config.default_solr_params = { 
      :qf => 'title_tesim author_tesim',
      :qt => 'search',
      :rows => 10  
    }
```
in ` app/controllers/catalog_controller.rb` I get:
```
ActionView::Template::Error (undefined method `to_model' for #<ActiveSupport::HashWithIndifferentAccess:0x0000000594cc58>):
    11:          <span class="document-counter">
    12:          <%= t('blacklight.search.documents.counter', :counter => counter) if counter %>
    13:          </span>
    14:          <%= link_to_document document, :label=>document_show_link_field(document), :counter => counter %>
    15:         </h5>
    16: 
    17:         <% # bookmark functions for items/docs -%>
```
error in my console log. 

And in my browser I get (Image attached):
```
Extracted source (around line #49):                
  # with all of the original params and block
  def method_missing(m, *args, &b)
    @_source.send(m, *args, &b)
  end

  def [] *args
``` 
![gitissue](https://cloud.githubusercontent.com/assets/4374028/5966449/6ee382b8-a82a-11e4-8693-2b1ef647296b.jpeg)

 
Any suggestion for what could be done to solve this problem?

**Comment by jcoyne** [comment]
This is the same issue as #64. The quick fix is to make sure you are using Rails 4.1.9 (you were using Rails 4.2.0).  We will soon release hydra 7.1.1 and 7.2.0 that will rectify this issue.
