### ISSUE TITLE
Hydra 7.x is broken under Rails 4.2.x

### ISSUE THREAD

**Issue by barmintor** [projecthydra/hydra#64]
Blacklight before 5.7.2 is broken with Rails 4.2.x, so the Hydra 7.x gem must either be pegged to Rails 4.1 or have it's Blacklight spec loosened a la https://github.com/projecthydra/hydra-head/commit/3b3341a95415aa39e3d6ddafaa9a8aa9d009348a

The result of this change is the problem reported at: https://groups.google.com/forum/#!topic/hydra-tech/qLPqC49fhEE

ActionView::Template::Error (undefined method `to_model' for #<ActiveSupport::HashWithIndifferentAccess:0x0000000594cc58>):

**Comment by jcoyne** [comment]
I propose we make 7.1.1 with a rails constraint. Then we can make 7.2.0 with blacklight bumped to >= 5.7.2 and without the rails constraint.  Thanks for tracking this one down @barmintor!

**Comment by barmintor** [comment]
+1 this plan

**Comment by jcoyne** [comment]
Released 7.1.1 and 7.2.0, both of which fix this issue.
