### ISSUE TITLE
add rake jetty:config to Dive into Hydra

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/hydra#70]
There should be something about it here: https://github.com/projecthydra/hydra/wiki/Lesson%3A-install-hydra-jetty

**Comment by mark-dce** [comment]
@jcoyne  - this seems redundant - it's already done by `rails g hydra:jetty` - no?

**Comment by bess** [comment]
Closing this issue, since hydra-jetty has been replaced by solr_wrapper.
