### ISSUE TITLE
Mistake in the "LDP Containers for the perplexed" wiki page

### ISSUE THREAD

**Issue by iherman** [projecthydra/hydra#77]
The [wiki page](https://github.com/projecthydra/hydra/wiki/LDP-Containers-for-the-perplexed) contains:

    </blog/entry1/> a ldp:DirectContainer .
      </blog/entry1/> a ldp:membershipResource </blog/comments> .
      </blog/entry1/> a ldp:hasMemberRelation hasComment .
      </blog/entry1/> ldp:contains </blog/entry1/comments1> .

which is clearly buggy, the second and third lines are not RDF triples...

**Comment by mjgiarlo** [comment]
Fixed!  Thanks.
