### ISSUE TITLE
Hydra 9.1.0rc is incompatible with last 3 minor releases of ActiveFedora

### ISSUE THREAD

**Issue by barmintor** [projecthydra/hydra#85]
Among other things, you cannot build experiments against any of the hydra-labs aggregation or pcdm gems without hydra and hydra-head supporting something later than AF 9.1.x

I am trying to put another RC together, but the Doubletree network is slow.

**Comment by mark-dce** [comment]
I'm trying to work through the Dive-Into-Hydra tutorial and running into this when I start my rails server and try to hit http://localhost:3000 :

```
Ldp::HttpError
STATUS: 503 ...

Extracted source (around line #108):
106
107
108
109
110
111
              
    resp.tap do |resp|
      unless resp.success?
        raise case resp.status
          when 400
            if resp.env.method == :head
              # If the request was a HEAD request (which only retrieves HTTP headers),

Rails.root: /home/vagrant/hydra-demo

Application Trace | Framework Trace | Full Trace
ldp (0.3.1) lib/ldp/client/methods.rb:108:in `block in check_for_errors'
ldp (0.3.1) lib/ldp/client/methods.rb:106:in `tap'
ldp (0.3.1) lib/ldp/client/methods.rb:106:in `check_for_errors'
ldp (0.3.1) lib/ldp/client/methods.rb:24:in `head'
active-fedora (9.1.2) lib/active_fedora/fedora.rb:41:in `init_base_path'
active-fedora (9.1.2) lib/active_fedora/fedora.rb:5:in `initialize'
active-fedora (9.1.2) lib/active_fedora.rb:207:in `new'
active-fedora (9.1.2) lib/active_fedora.rb:207:in `fedora'
active-fedora (9.1.2) lib/active_fedora/ldp_cache.rb:40:in `reset_cache_settings'
active-fedora (9.1.2) lib/active_fedora/ldp_cache.rb:33:in `rescue in call'
active-fedora (9.1.2) lib/active_fedora/ldp_cache.rb:24:in `call'
activerecord (4.2.4) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.4) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.2.1) lib/web_console/middleware.rb:31:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
railties (4.2.4) lib/rails/engine.rb:518:in `call'
railties (4.2.4) lib/rails/application.rb:165:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
/home/vagrant/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/home/vagrant/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/home/vagrant/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by jcoyne** [comment]
@mark-DCE that's an error on the Fedora server. Which version of Fedora are you running?

**Comment by mark-dce** [comment]
Ahhh, I'd assume I'm running the version currently included in hydra-jetty master [9793532](https://github.com/projecthydra/hydra-jetty/tree/9793532d92a7be6e14b1ff80014eb35b4e446187)

**Comment by roryegerton** [comment]
Hi Folks,

Can I just ask did you get a solution to this problem. I am currently trying to follow the Dive into Hydra steps and only started today. I am on step 4: "start the application & search for results" .... When I visit localhost:3000 ..... I get a very similar message to Mark

Also to note I am using Centos 7 in a VM, not sure if there is a possible protocol issue beacuse of this?

Any help appreciated

ERROR:
Ldp::HttpError
STATUS: 502 ...

CODE:
    resp.tap do |resp|
      unless resp.success?
        raise case resp.status
          when 400
            if resp.env.method == :head
              # If the request was a HEAD request (which only retrieves HTTP headers),

TRACE:
ldp (0.4.1) lib/ldp/client/methods.rb:121:in `block in check_for_errors'
ldp (0.4.1) lib/ldp/client/methods.rb:119:in `tap'
ldp (0.4.1) lib/ldp/client/methods.rb:119:in `check_for_errors'
ldp (0.4.1) lib/ldp/client/methods.rb:25:in `block in head'
activesupport (4.2.4) lib/active_support/notifications.rb:166:in `instrument'
ldp (0.4.1) lib/ldp/client/methods.rb:17:in `head'
active-fedora (9.7.0) lib/active_fedora/fedora.rb:45:in `init_base_path'
active-fedora (9.7.0) lib/active_fedora/fedora.rb:5:in `initialize'
active-fedora (9.7.0) lib/active_fedora.rb:226:in `new'
active-fedora (9.7.0) lib/active_fedora.rb:226:in `fedora'
active-fedora (9.7.0) lib/active_fedora/ldp_cache.rb:40:in `reset_cache_settings'
active-fedora (9.7.0) lib/active_fedora/ldp_cache.rb:33:in `rescue in call'
active-fedora (9.7.0) lib/active_fedora/ldp_cache.rb:24:in `call'
activerecord (4.2.4) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.4) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
railties (4.2.4) lib/rails/engine.rb:518:in `call'
railties (4.2.4) lib/rails/application.rb:165:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'

**Comment by aaronisbrewing** [comment]
Is there any update to this? A solution?

**Comment by roryegerton** [comment]
We were behind a corporate firewall. So our HTTP_PROXY env variable are set on our machines. 

I think possibly the faraday repo was making all LDP requests through the proxy. Even requests to  localhost.

There was a a pull request on faraday to ignore the proxy for requests localhost, so we forked this repo and merged the pull request.

This is our fork: https://github.com/NLIreland/faraday

**Comment by rkhet** [comment]
Thanks for the proxy tip.

**Comment by jcoyne** [comment]
Try 9.1.0.rc5
