### ISSUE TITLE
no more jetty

### ISSUE THREAD

**Issue by rkhet** [projecthydra/hydra#98]
On the Lesson Start FCRepo and Solr, Dive Into page are instructions to run "solr_wrapper".  It's not present in the new demo dir, nor is a jetty/webapp dir anywhere.  Did I skip something?
-rkh

**Comment by jcoyne** [comment]
`solr_wrapper` is a binary in a gem that is installed by hydra. Solr 5 is now a standalone server and you can't put it in a servlet container as you did with Solr 4.

**Comment by rkhet** [comment]
Thx, found it.
